%% =============================================================================================
% ================================= Spike Extraction Software ==================================
% ================================ Presented by: Reza Saadatyar ================================
% ============================= E-mail: Reza.Saadatyar@outlook.com =============================
% ======================================= 2019-2020 ============================================

function help(tab6)
uicontrol('parent',tab6,'style','text','string','List of Abbreviations:','unit','norm','Position',...
[0.06 0.9 0.9 0.1],'Fontweight','bold','FontSize',20,'FontName','Times New Roman');
uicontrol('parent',tab6,'style','text','string',{'Filtering:';'Sampling frequency (Fs)';...
'Lower cutoff frequency (Flow)';'Higher cutoff frequency (Fhigh)';'Passband ripple (Rp)';...
'Stopband attenuation (Rs)'},'unit','norm','Position',[0.02 0.6 0.2 0.3],'Fontweight',...
'bold','FontSize',12,'FontName','Times New Roman','HorizontalAlignment','left',...
'ForegroundColor',[0.49 0.18 0.56]);

uicontrol('parent',tab6,'style','text','string',{'Feature Exraction:';'Wavelet Transform (WT)';....
'Principle Component Analysis (PCA)'},'unit','norm','Position',[0.2 0.17 0.2 0.73],...
'Fontweight','bold','FontSize',12,'FontName','Times New Roman','HorizontalAlignment','left',...
'ForegroundColor',[0.64 0.08 0.18]);

uicontrol('parent',tab6,'style','text','string',{'Clustring:';'Fuzzy C-Means Clustering (FCM)';...
'K-means'},'unit','norm','Position',[0.41 0.5 0.2 0.41],...
'HorizontalAlignment','left','ForegroundColor','b','FontSize',12,'Fontweight','bold','FontName',...
'Times New Roman');

uicontrol('parent',tab6,'style','text','string',{'Firing Rate (FR)';'Inter-Spike Intervals (ISI)';...
'Autocorrelogram'},'unit','norm','Position',[0.62 0.5 0.15 0.4],'Fontweight',...
'bold','FontSize',12,'FontName','Times New Roman','HorizontalAlignment','left','ForegroundColor','k');
end

 

